default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: wish_development

test:
  <<: *default
  database: wish_test

production:
  <<: *default
  database: wish_production
  username: wish
  password: <%= ENV['WISH_DATABASE_PASSWORD'] %>
